- name: VM1'e quotea web sitesi, app.py ve nginx kurulumu
  hosts: vm1
  become: yes
  vars:
    web_root: /opt/quotea
  tasks:
    - name: Nginx kur
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: quotea klasörünü kopyala
      copy:
        src: ./quotea/
        dest: "{{ web_root }}/"
        mode: 0755

    - name: app.py için systemd servisi oluştur
      copy:
        dest: /etc/systemd/system/quotea-api.service
        content: |
          [Unit]
          Description=Quotea Flask API
          After=network.target

          [Service]
          User={{ ansible_user }}
          WorkingDirectory={{ web_root }}
          ExecStart=/usr/bin/python3 {{ web_root }}/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Servisi başlat ve enable et
      systemd:
        name: quotea-api
        state: started
        enabled: yes

    - name: Nginx site konfigürasyonu oluştur
      copy:
        dest: /etc/nginx/sites-available/quotea
        content: |
          server {
              listen 80;
              server_name _;
              root {{ web_root }};
              index index.html;
              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Nginx siteyi etkinleştir
      file:
        src: /etc/nginx/sites-available/quotea
        dest: /etc/nginx/sites-enabled/quotea
        state: link
        force: yes

    - name: Varsayılan nginx sitesini kaldır
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Nginx'i yeniden başlat
      service:
        name: nginx
        state: restarted

- name: VM2'ye quotea web sitesi ve nginx kurulumu
  hosts: vm2
  become: yes
  vars:
    web_root: /opt/quotea
    vm1_internal_ip: 10.164.0.11  # VM1'in internal IP'si
  tasks:
    - name: Nginx kur
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: quotea klasörünü kopyala
      copy:
        src: ./quotea/
        dest: "{{ web_root }}/"
        mode: 0755

    - name: scripts.js dosyasında fetch'i VM1 IP'sine göre ayarla
      replace:
        path: "{{ web_root }}/scripts.js"
        regexp: "fetch\\('.*?/api/sentences'\\)"
        replace: "fetch('http://{{ vm1_internal_ip }}:5000/api/sentences')"

    - name: Nginx site konfigürasyonu oluştur
      copy:
        dest: /etc/nginx/sites-available/quotea
        content: |
          server {
              listen 80;
              server_name _;
              root {{ web_root }};
              index index.html;
              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Nginx siteyi etkinleştir
      file:
        src: /etc/nginx/sites-available/quotea
        dest: /etc/nginx/sites-enabled/quotea
        state: link
        force: yes

    - name: Varsayılan nginx sitesini kaldır
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Nginx'i yeniden başlat
      service:
        name: nginx
        state: restarted