- name: VM2'ye quotea web sitesi ve nginx kurulumu
  hosts: vm2
  become: yes
  vars:
    web_root: /opt/quotea
    vm1_backend_ip: 10.164.0.15  # VM1'in iç ağ IP adresi (güncellendi)
  tasks:
    - name: Python3 ve pip kur
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Gerekli Python paketlerini kur
      pip:
        name:
          - flask
          - flask-cors
          - psycopg2-binary
        executable: pip3

    - name: Nginx kur
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: quotea klasörünü kopyala
      copy:
        src: ./quotea/
        dest: "{{ web_root }}/"
        mode: 0755

    - name: app.py için systemd servisi oluştur
      copy:
        dest: /etc/systemd/system/quotea-api.service
        content: |
          [Unit]
          Description=Quotea Flask API
          After=network.target

          [Service]
          User=adnan@white-takke-home
          WorkingDirectory={{ web_root }}
          ExecStart=/usr/bin/python3 {{ web_root }}/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Servisi başlat ve enable et
      systemd:
        name: quotea-api
        state: started
        enabled: yes

    - name: Nginx site konfigürasyonu oluştur
      copy:
        dest: /etc/nginx/sites-available/quotea
        content: |
          server {
              listen 80;
              server_name _;
              root {{ web_root }};
              index index.html;

              location /api/sentences {
                  proxy_pass http://{{ vm1_backend_ip }}:5757/api/sentences;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location /api/vm-info {
                  proxy_pass http://localhost:5757/api/vm-info;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Nginx siteyi etkinleştir
      file:
        src: /etc/nginx/sites-available/quotea
        dest: /etc/nginx/sites-enabled/quotea
        state: link
        force: yes

    - name: Varsayılan nginx sitesini kaldır
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Nginx'i yeniden başlat
      service:
        name: nginx
        state: restarted
