- name: VM2'ye quotea web sitesi ve nginx kurulumu
  hosts: vm2
  become: yes
  vars:
    web_root: /opt/quotea
    vm1_backend_ip: 10.164.0.15  # VM1'in iç ağ IP adresi
  tasks:
    - name: Nginx kur
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: quotea klasörünü kopyala
      copy:
        src: ./quotea/
        dest: "{{ web_root }}/"
        mode: 0755
        
    - name: Nginx site konfigürasyonu oluştur
      copy:
        dest: /etc/nginx/sites-available/quotea
        content: |
          server {
              listen 80;
              server_name _;
              root {{ web_root }};
              index index.html;

              location /api/sentences {
                  proxy_pass http://{{ vm1_backend_ip }}:5757/api/sentences;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location /api/vm-info {
                  proxy_pass http://localhost:5757/api/vm-info;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Nginx siteyi etkinleştir
      file:
        src: /etc/nginx/sites-available/quotea
        dest: /etc/nginx/sites-enabled/quotea
        state: link
        force: yes

    - name: Varsayılan nginx sitesini kaldır
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Nginx'i yeniden başlat
      service:
        name: nginx
        state: restarted
